//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "StoreItem", "Store", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.ItemCategory), "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.Item), true)]
[assembly: EdmRelationshipAttribute("Model1", "ConsumerOrder", "Consumer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.Consumer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.Order), true)]
[assembly: EdmRelationshipAttribute("Model1", "EmployeeOrder", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.Employee), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.Order), true)]
[assembly: EdmRelationshipAttribute("Model1", "OrderPosition", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.Order), "Position", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.Position), true)]
[assembly: EdmRelationshipAttribute("Model1", "AppointmentEmployee", "Appointment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.Appointment), "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.Employee), true)]
[assembly: EdmRelationshipAttribute("Model1", "PositionItem", "Position", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.Position), "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.Item), true)]
[assembly: EdmRelationshipAttribute("Model1", "ParameterCategoryItemParameter", "ParameterCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.ParameterCategory), "ItemParameter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.ItemParameter), true)]
[assembly: EdmRelationshipAttribute("Model1", "ItemItemParameter", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.Item), "ItemParameter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.ItemParameter), true)]
[assembly: EdmRelationshipAttribute("Model1", "ItemCategorypureJoin_IPcats", "ItemCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.ItemCategory), "pureJoin_IPcats", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.pureJoin_IPcats), true)]
[assembly: EdmRelationshipAttribute("Model1", "ParameterCategorypureJoin_IPcats", "ParameterCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SERIOUS_BUSINESS.res.ParameterCategory), "pureJoin_IPcats", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SERIOUS_BUSINESS.res.pureJoin_IPcats), true)]

#endregion

namespace SERIOUS_BUSINESS.res
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> OrderSet
        {
            get
            {
                if ((_OrderSet == null))
                {
                    _OrderSet = base.CreateObjectSet<Order>("OrderSet");
                }
                return _OrderSet;
            }
        }
        private ObjectSet<Order> _OrderSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> EmployeeSet
        {
            get
            {
                if ((_EmployeeSet == null))
                {
                    _EmployeeSet = base.CreateObjectSet<Employee>("EmployeeSet");
                }
                return _EmployeeSet;
            }
        }
        private ObjectSet<Employee> _EmployeeSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Consumer> ConsumerSet
        {
            get
            {
                if ((_ConsumerSet == null))
                {
                    _ConsumerSet = base.CreateObjectSet<Consumer>("ConsumerSet");
                }
                return _ConsumerSet;
            }
        }
        private ObjectSet<Consumer> _ConsumerSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemCategory> ItemCategorySet
        {
            get
            {
                if ((_ItemCategorySet == null))
                {
                    _ItemCategorySet = base.CreateObjectSet<ItemCategory>("ItemCategorySet");
                }
                return _ItemCategorySet;
            }
        }
        private ObjectSet<ItemCategory> _ItemCategorySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> ItemSet
        {
            get
            {
                if ((_ItemSet == null))
                {
                    _ItemSet = base.CreateObjectSet<Item>("ItemSet");
                }
                return _ItemSet;
            }
        }
        private ObjectSet<Item> _ItemSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Position> PositionSet
        {
            get
            {
                if ((_PositionSet == null))
                {
                    _PositionSet = base.CreateObjectSet<Position>("PositionSet");
                }
                return _PositionSet;
            }
        }
        private ObjectSet<Position> _PositionSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Appointment> AppointmentSet
        {
            get
            {
                if ((_AppointmentSet == null))
                {
                    _AppointmentSet = base.CreateObjectSet<Appointment>("AppointmentSet");
                }
                return _AppointmentSet;
            }
        }
        private ObjectSet<Appointment> _AppointmentSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemParameter> ItemParameterSet
        {
            get
            {
                if ((_ItemParameterSet == null))
                {
                    _ItemParameterSet = base.CreateObjectSet<ItemParameter>("ItemParameterSet");
                }
                return _ItemParameterSet;
            }
        }
        private ObjectSet<ItemParameter> _ItemParameterSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ParameterCategory> ParameterCategorySet
        {
            get
            {
                if ((_ParameterCategorySet == null))
                {
                    _ParameterCategorySet = base.CreateObjectSet<ParameterCategory>("ParameterCategorySet");
                }
                return _ParameterCategorySet;
            }
        }
        private ObjectSet<ParameterCategory> _ParameterCategorySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pureJoin_IPcats> pureJoin_IPcatsSet
        {
            get
            {
                if ((_pureJoin_IPcatsSet == null))
                {
                    _pureJoin_IPcatsSet = base.CreateObjectSet<pureJoin_IPcats>("pureJoin_IPcatsSet");
                }
                return _pureJoin_IPcatsSet;
            }
        }
        private ObjectSet<pureJoin_IPcats> _pureJoin_IPcatsSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stock_for_Stock> Stock_for_Stock
        {
            get
            {
                if ((_Stock_for_Stock == null))
                {
                    _Stock_for_Stock = base.CreateObjectSet<Stock_for_Stock>("Stock_for_Stock");
                }
                return _Stock_for_Stock;
            }
        }
        private ObjectSet<Stock_for_Stock> _Stock_for_Stock;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderSet(Order order)
        {
            base.AddObject("OrderSet", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmployeeSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployeeSet(Employee employee)
        {
            base.AddObject("EmployeeSet", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConsumerSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsumerSet(Consumer consumer)
        {
            base.AddObject("ConsumerSet", consumer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemCategorySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemCategorySet(ItemCategory itemCategory)
        {
            base.AddObject("ItemCategorySet", itemCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemSet(Item item)
        {
            base.AddObject("ItemSet", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PositionSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPositionSet(Position position)
        {
            base.AddObject("PositionSet", position);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppointmentSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppointmentSet(Appointment appointment)
        {
            base.AddObject("AppointmentSet", appointment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemParameterSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemParameterSet(ItemParameter itemParameter)
        {
            base.AddObject("ItemParameterSet", itemParameter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ParameterCategorySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParameterCategorySet(ParameterCategory parameterCategory)
        {
            base.AddObject("ParameterCategorySet", parameterCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pureJoin_IPcatsSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopureJoin_IPcatsSet(pureJoin_IPcats pureJoin_IPcats)
        {
            base.AddObject("pureJoin_IPcatsSet", pureJoin_IPcats);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stock_for_Stock EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStock_for_Stock(Stock_for_Stock stock_for_Stock)
        {
            base.AddObject("Stock_for_Stock", stock_for_Stock);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Appointment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Appointment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Appointment object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Appointment CreateAppointment(global::System.Int32 id, global::System.String name)
        {
            Appointment appointment = new Appointment();
            appointment.id = id;
            appointment.name = name;
            return appointment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 accessModifier
        {
            get
            {
                return _accessModifier;
            }
            set
            {
                OnaccessModifierChanging(value);
                ReportPropertyChanging("accessModifier");
                _accessModifier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("accessModifier");
                OnaccessModifierChanged();
            }
        }
        private global::System.Int16 _accessModifier = 0;
        partial void OnaccessModifierChanging(global::System.Int16 value);
        partial void OnaccessModifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "AppointmentEmployee", "Employee")]
        public EntityCollection<Employee> Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("Model1.AppointmentEmployee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("Model1.AppointmentEmployee", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Consumer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consumer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Consumer object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static Consumer CreateConsumer(global::System.String name, global::System.String phone, global::System.String email, global::System.Int32 id)
        {
            Consumer consumer = new Consumer();
            consumer.name = name;
            consumer.phone = phone;
            consumer.email = email;
            consumer.id = id;
            return consumer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ConsumerOrder", "Order")]
        public EntityCollection<Order> Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("Model1.ConsumerOrder", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("Model1.ConsumerOrder", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="login">Initial value of the login property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="aptID">Initial value of the aptID property.</param>
        public static Employee CreateEmployee(global::System.Int32 id, global::System.String name, global::System.String login, global::System.String password, global::System.Int32 aptID)
        {
            Employee employee = new Employee();
            employee.id = id;
            employee.name = name;
            employee.login = login;
            employee.password = password;
            employee.aptID = aptID;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 aptID
        {
            get
            {
                return _aptID;
            }
            set
            {
                OnaptIDChanging(value);
                ReportPropertyChanging("aptID");
                _aptID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aptID");
                OnaptIDChanged();
            }
        }
        private global::System.Int32 _aptID;
        partial void OnaptIDChanging(global::System.Int32 value);
        partial void OnaptIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "EmployeeOrder", "Order")]
        public EntityCollection<Order> Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("Model1.EmployeeOrder", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("Model1.EmployeeOrder", "Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "AppointmentEmployee", "Appointment")]
        public Appointment Appointment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Appointment>("Model1.AppointmentEmployee", "Appointment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Appointment>("Model1.AppointmentEmployee", "Appointment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Appointment> AppointmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Appointment>("Model1.AppointmentEmployee", "Appointment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Appointment>("Model1.AppointmentEmployee", "Appointment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="storeResidue">Initial value of the storeResidue property.</param>
        /// <param name="demand">Initial value of the demand property.</param>
        /// <param name="catID">Initial value of the catID property.</param>
        public static Item CreateItem(global::System.Int32 id, global::System.Int32 storeResidue, global::System.Int32 demand, global::System.Int32 catID)
        {
            Item item = new Item();
            item.id = id;
            item.storeResidue = storeResidue;
            item.demand = demand;
            item.catID = catID;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 storeResidue
        {
            get
            {
                return _storeResidue;
            }
            set
            {
                OnstoreResidueChanging(value);
                ReportPropertyChanging("storeResidue");
                _storeResidue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("storeResidue");
                OnstoreResidueChanged();
            }
        }
        private global::System.Int32 _storeResidue;
        partial void OnstoreResidueChanging(global::System.Int32 value);
        partial void OnstoreResidueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 demand
        {
            get
            {
                return _demand;
            }
            set
            {
                OndemandChanging(value);
                ReportPropertyChanging("demand");
                _demand = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("demand");
                OndemandChanged();
            }
        }
        private global::System.Int32 _demand;
        partial void OndemandChanging(global::System.Int32 value);
        partial void OndemandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 catID
        {
            get
            {
                return _catID;
            }
            set
            {
                OncatIDChanging(value);
                ReportPropertyChanging("catID");
                _catID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("catID");
                OncatIDChanged();
            }
        }
        private global::System.Int32 _catID;
        partial void OncatIDChanging(global::System.Int32 value);
        partial void OncatIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "StoreItem", "Store")]
        public ItemCategory Store
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemCategory>("Model1.StoreItem", "Store").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemCategory>("Model1.StoreItem", "Store").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ItemCategory> StoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemCategory>("Model1.StoreItem", "Store");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ItemCategory>("Model1.StoreItem", "Store", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ItemItemParameter", "ItemParameter")]
        public EntityCollection<ItemParameter> ItemParameter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemParameter>("Model1.ItemItemParameter", "ItemParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemParameter>("Model1.ItemItemParameter", "ItemParameter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "PositionItem", "Position")]
        public EntityCollection<Position> Position
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Position>("Model1.PositionItem", "Position");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Position>("Model1.PositionItem", "Position", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ItemCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemCategory object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static ItemCategory CreateItemCategory(global::System.String name, global::System.Int32 id)
        {
            ItemCategory itemCategory = new ItemCategory();
            itemCategory.name = name;
            itemCategory.id = id;
            return itemCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "StoreItem", "Item")]
        public EntityCollection<Item> Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Item>("Model1.StoreItem", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Item>("Model1.StoreItem", "Item", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ItemCategorypureJoin_IPcats", "pureJoin_IPcats")]
        public EntityCollection<pureJoin_IPcats> pureJoin_IPcats
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pureJoin_IPcats>("Model1.ItemCategorypureJoin_IPcats", "pureJoin_IPcats");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pureJoin_IPcats>("Model1.ItemCategorypureJoin_IPcats", "pureJoin_IPcats", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ItemParameter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemParameter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemParameter object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="itemID">Initial value of the itemID property.</param>
        /// <param name="paramCatID">Initial value of the paramCatID property.</param>
        public static ItemParameter CreateItemParameter(global::System.Int32 id, global::System.Int32 itemID, global::System.Int32 paramCatID)
        {
            ItemParameter itemParameter = new ItemParameter();
            itemParameter.id = id;
            itemParameter.itemID = itemID;
            itemParameter.paramCatID = paramCatID;
            return itemParameter;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valueDbl
        {
            get
            {
                return _valueDbl;
            }
            set
            {
                OnvalueDblChanging(value);
                ReportPropertyChanging("valueDbl");
                _valueDbl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valueDbl");
                OnvalueDblChanged();
            }
        }
        private Nullable<global::System.Double> _valueDbl;
        partial void OnvalueDblChanging(Nullable<global::System.Double> value);
        partial void OnvalueDblChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> valueBool
        {
            get
            {
                return _valueBool;
            }
            set
            {
                OnvalueBoolChanging(value);
                ReportPropertyChanging("valueBool");
                _valueBool = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valueBool");
                OnvalueBoolChanged();
            }
        }
        private Nullable<global::System.Boolean> _valueBool;
        partial void OnvalueBoolChanging(Nullable<global::System.Boolean> value);
        partial void OnvalueBoolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String valueTxt
        {
            get
            {
                return _valueTxt;
            }
            set
            {
                OnvalueTxtChanging(value);
                ReportPropertyChanging("valueTxt");
                _valueTxt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("valueTxt");
                OnvalueTxtChanged();
            }
        }
        private global::System.String _valueTxt;
        partial void OnvalueTxtChanging(global::System.String value);
        partial void OnvalueTxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 itemID
        {
            get
            {
                return _itemID;
            }
            set
            {
                OnitemIDChanging(value);
                ReportPropertyChanging("itemID");
                _itemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("itemID");
                OnitemIDChanged();
            }
        }
        private global::System.Int32 _itemID;
        partial void OnitemIDChanging(global::System.Int32 value);
        partial void OnitemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 paramCatID
        {
            get
            {
                return _paramCatID;
            }
            set
            {
                OnparamCatIDChanging(value);
                ReportPropertyChanging("paramCatID");
                _paramCatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paramCatID");
                OnparamCatIDChanged();
            }
        }
        private global::System.Int32 _paramCatID;
        partial void OnparamCatIDChanging(global::System.Int32 value);
        partial void OnparamCatIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ParameterCategoryItemParameter", "ParameterCategory")]
        public ParameterCategory ParameterCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParameterCategory>("Model1.ParameterCategoryItemParameter", "ParameterCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParameterCategory>("Model1.ParameterCategoryItemParameter", "ParameterCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ParameterCategory> ParameterCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParameterCategory>("Model1.ParameterCategoryItemParameter", "ParameterCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ParameterCategory>("Model1.ParameterCategoryItemParameter", "ParameterCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ItemItemParameter", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model1.ItemItemParameter", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model1.ItemItemParameter", "Item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model1.ItemItemParameter", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("Model1.ItemItemParameter", "Item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="consID">Initial value of the consID property.</param>
        /// <param name="emplID">Initial value of the emplID property.</param>
        public static Order CreateOrder(global::System.Int32 id, global::System.DateTime date, global::System.String status, global::System.Int32 consID, global::System.Int32 emplID)
        {
            Order order = new Order();
            order.id = id;
            order.date = date;
            order.status = status;
            order.consID = consID;
            order.emplID = emplID;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 consID
        {
            get
            {
                return _consID;
            }
            set
            {
                OnconsIDChanging(value);
                ReportPropertyChanging("consID");
                _consID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("consID");
                OnconsIDChanged();
            }
        }
        private global::System.Int32 _consID;
        partial void OnconsIDChanging(global::System.Int32 value);
        partial void OnconsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emplID
        {
            get
            {
                return _emplID;
            }
            set
            {
                OnemplIDChanging(value);
                ReportPropertyChanging("emplID");
                _emplID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("emplID");
                OnemplIDChanged();
            }
        }
        private global::System.Int32 _emplID;
        partial void OnemplIDChanging(global::System.Int32 value);
        partial void OnemplIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ConsumerOrder", "Consumer")]
        public Consumer Consumer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consumer>("Model1.ConsumerOrder", "Consumer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consumer>("Model1.ConsumerOrder", "Consumer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Consumer> ConsumerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consumer>("Model1.ConsumerOrder", "Consumer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Consumer>("Model1.ConsumerOrder", "Consumer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "EmployeeOrder", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("Model1.EmployeeOrder", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("Model1.EmployeeOrder", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("Model1.EmployeeOrder", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("Model1.EmployeeOrder", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "OrderPosition", "Position")]
        public EntityCollection<Position> Position
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Position>("Model1.OrderPosition", "Position");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Position>("Model1.OrderPosition", "Position", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ParameterCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ParameterCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ParameterCategory object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="type">Initial value of the type property.</param>
        public static ParameterCategory CreateParameterCategory(global::System.Int32 id, global::System.String name, global::System.Int16 type)
        {
            ParameterCategory parameterCategory = new ParameterCategory();
            parameterCategory.id = id;
            parameterCategory.name = name;
            parameterCategory.type = type;
            return parameterCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Int16 _type;
        partial void OntypeChanging(global::System.Int16 value);
        partial void OntypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ParameterCategoryItemParameter", "ItemParameter")]
        public EntityCollection<ItemParameter> ItemParameter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemParameter>("Model1.ParameterCategoryItemParameter", "ItemParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemParameter>("Model1.ParameterCategoryItemParameter", "ItemParameter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ParameterCategorypureJoin_IPcats", "pureJoin_IPcats")]
        public EntityCollection<pureJoin_IPcats> pureJoin_IPcats
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pureJoin_IPcats>("Model1.ParameterCategorypureJoin_IPcats", "pureJoin_IPcats");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pureJoin_IPcats>("Model1.ParameterCategorypureJoin_IPcats", "pureJoin_IPcats", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Position")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Position : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Position object.
        /// </summary>
        /// <param name="orderID">Initial value of the orderID property.</param>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="count">Initial value of the count property.</param>
        /// <param name="itemID">Initial value of the itemID property.</param>
        public static Position CreatePosition(global::System.Int32 orderID, global::System.Int32 id, global::System.Int32 count, global::System.Int32 itemID)
        {
            Position position = new Position();
            position.orderID = orderID;
            position.id = id;
            position.count = count;
            position.itemID = itemID;
            return position;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderID
        {
            get
            {
                return _orderID;
            }
            set
            {
                OnorderIDChanging(value);
                ReportPropertyChanging("orderID");
                _orderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderID");
                OnorderIDChanged();
            }
        }
        private global::System.Int32 _orderID;
        partial void OnorderIDChanging(global::System.Int32 value);
        partial void OnorderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 count
        {
            get
            {
                return _count;
            }
            set
            {
                OncountChanging(value);
                ReportPropertyChanging("count");
                _count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("count");
                OncountChanged();
            }
        }
        private global::System.Int32 _count;
        partial void OncountChanging(global::System.Int32 value);
        partial void OncountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 itemID
        {
            get
            {
                return _itemID;
            }
            set
            {
                OnitemIDChanging(value);
                ReportPropertyChanging("itemID");
                _itemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("itemID");
                OnitemIDChanged();
            }
        }
        private global::System.Int32 _itemID;
        partial void OnitemIDChanging(global::System.Int32 value);
        partial void OnitemIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "OrderPosition", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("Model1.OrderPosition", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("Model1.OrderPosition", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("Model1.OrderPosition", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("Model1.OrderPosition", "Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "PositionItem", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model1.PositionItem", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model1.PositionItem", "Item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model1.PositionItem", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("Model1.PositionItem", "Item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="pureJoin_IPcats")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pureJoin_IPcats : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pureJoin_IPcats object.
        /// </summary>
        /// <param name="iCID">Initial value of the ICID property.</param>
        /// <param name="pCID">Initial value of the PCID property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static pureJoin_IPcats CreatepureJoin_IPcats(global::System.Int32 iCID, global::System.Int32 pCID, global::System.Int32 id)
        {
            pureJoin_IPcats pureJoin_IPcats = new pureJoin_IPcats();
            pureJoin_IPcats.ICID = iCID;
            pureJoin_IPcats.PCID = pCID;
            pureJoin_IPcats.id = id;
            return pureJoin_IPcats;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ICID
        {
            get
            {
                return _ICID;
            }
            set
            {
                if (_ICID != value)
                {
                    OnICIDChanging(value);
                    ReportPropertyChanging("ICID");
                    _ICID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ICID");
                    OnICIDChanged();
                }
            }
        }
        private global::System.Int32 _ICID;
        partial void OnICIDChanging(global::System.Int32 value);
        partial void OnICIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PCID
        {
            get
            {
                return _PCID;
            }
            set
            {
                if (_PCID != value)
                {
                    OnPCIDChanging(value);
                    ReportPropertyChanging("PCID");
                    _PCID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PCID");
                    OnPCIDChanged();
                }
            }
        }
        private global::System.Int32 _PCID;
        partial void OnPCIDChanging(global::System.Int32 value);
        partial void OnPCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ItemCategorypureJoin_IPcats", "ItemCategory")]
        public ItemCategory ItemCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemCategory>("Model1.ItemCategorypureJoin_IPcats", "ItemCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemCategory>("Model1.ItemCategorypureJoin_IPcats", "ItemCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ItemCategory> ItemCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemCategory>("Model1.ItemCategorypureJoin_IPcats", "ItemCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ItemCategory>("Model1.ItemCategorypureJoin_IPcats", "ItemCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ParameterCategorypureJoin_IPcats", "ParameterCategory")]
        public ParameterCategory ParameterCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParameterCategory>("Model1.ParameterCategorypureJoin_IPcats", "ParameterCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParameterCategory>("Model1.ParameterCategorypureJoin_IPcats", "ParameterCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ParameterCategory> ParameterCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParameterCategory>("Model1.ParameterCategorypureJoin_IPcats", "ParameterCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ParameterCategory>("Model1.ParameterCategorypureJoin_IPcats", "ParameterCategory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Stock_for_Stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stock_for_Stock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stock_for_Stock object.
        /// </summary>
        /// <param name="спрос">Initial value of the Спрос property.</param>
        /// <param name="остаток">Initial value of the Остаток property.</param>
        public static Stock_for_Stock CreateStock_for_Stock(global::System.Int32 спрос, global::System.Int32 остаток)
        {
            Stock_for_Stock stock_for_Stock = new Stock_for_Stock();
            stock_for_Stock.Спрос = спрос;
            stock_for_Stock.Остаток = остаток;
            return stock_for_Stock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Наименование
        {
            get
            {
                return _Наименование;
            }
            set
            {
                OnНаименованиеChanging(value);
                ReportPropertyChanging("Наименование");
                _Наименование = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Наименование");
                OnНаименованиеChanged();
            }
        }
        private global::System.String _Наименование;
        partial void OnНаименованиеChanging(global::System.String value);
        partial void OnНаименованиеChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Спрос
        {
            get
            {
                return _Спрос;
            }
            set
            {
                if (_Спрос != value)
                {
                    OnСпросChanging(value);
                    ReportPropertyChanging("Спрос");
                    _Спрос = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Спрос");
                    OnСпросChanged();
                }
            }
        }
        private global::System.Int32 _Спрос;
        partial void OnСпросChanging(global::System.Int32 value);
        partial void OnСпросChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Остаток
        {
            get
            {
                return _Остаток;
            }
            set
            {
                if (_Остаток != value)
                {
                    OnОстатокChanging(value);
                    ReportPropertyChanging("Остаток");
                    _Остаток = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Остаток");
                    OnОстатокChanged();
                }
            }
        }
        private global::System.Int32 _Остаток;
        partial void OnОстатокChanging(global::System.Int32 value);
        partial void OnОстатокChanged();

        #endregion
    
    }

    #endregion
    
}
